### ISSUE TITLE
Ivy candidates is hard to read

### ISSUE THREAD

**Issue by BooAA** [sjrmanning/darkokai#12]
Most of the time dardokai theme works fine with ivy, but with certain candidates it's almost impossible to distinguish the text from the ivy background. See screenshot below 
![Screenshot from 2020-03-29 00-16-35](https://user-images.githubusercontent.com/32809182/77827878-1bbfcb80-7153-11ea-83d4-5a2c388bf8b7.png)

This is the result of counsel-describe-function with "^project find" as filter string, the middle part of last 2 items (project-or-external-find-file, project-or-external-find-regexp) is almost invisible.

**Comment by sjrmanning** [comment]
Sorry for the delay on this. I had a look and it seems like it was `ivy-highlight-face` causing issues when ivy highlights a result as a command. At first I set it to `nil` but you do lose a bit of functionality (being able to visually tell which is a command), so I'm going with the theme's gray color for now. Hope this helps!

**Comment by sjrmanning** [comment]
Going to close this for now, but if anyone has a nicer solution to this or if you think you'd prefer the `nil` variant, let me know :)
