### ISSUE TITLE
Spaceline's margin is too big

### ISSUE THREAD

**Issue by colin4124** [sjrmanning/darkokai#2]
![deepinscreenshot20160515202358](https://cloud.githubusercontent.com/assets/1255176/15274064/fba80c70-1adc-11e6-8056-2e372495ea6f.png)
![deepinscreenshot20160515202333](https://cloud.githubusercontent.com/assets/1255176/15274063/fb673236-1adc-11e6-8043-7e610b3ccfbd.png)

Would you change it to that as follow ?

![deepinscreenshot20160515204005](https://cloud.githubusercontent.com/assets/1255176/15274079/62fad6c8-1add-11e6-81da-4c5521604e23.png)

**Comment by sjrmanning** [comment]
You can use `(setq darkokai-mode-line-padding 1)` before you call `load-theme` to get that behaviour. I might change this to the default, but for now that should fix your problem.

**Comment by colin4124** [comment]
thx ^_^

**Comment by sjrmanning** [comment]
No worries!
