### ISSUE TITLE
Seperating whitespace between line-number and text missing

### ISSUE THREAD

**Issue by ghost** [sjrmanning/darkokai#4]
There's no seperating whitespace between line-number and text when I'm using emacs in the terminal, which sucks when it comes to copying text by selecting it using the mouse ... I'd be happy if you change this! Thanks in advance.

![screenshot_20161002_160300](https://cloud.githubusercontent.com/assets/12951830/19021082/c6b88a94-88b9-11e6-8728-7a3e5a78a86d.png)

**Comment by sjrmanning** [comment]
Weird, I haven't seen that before. What's your `linum-format` look like? I'm using `(setq linum-format " %4d ")` and it looks good in terminal.

**Comment by ghost** [comment]
I haven't set `linum-format` until now – it solves the problem. Thanks. I just thought that it should look the same regardless if I run emacs or emacs-nox …
