### ISSUE TITLE
Org-habits: * and ! not visible after applying darkokai

### ISSUE THREAD

**Issue by mschwld** [sjrmanning/darkokai#8]
Hey, if i apply the darkokai theme i can't see the * * * * * and ! ! ! ! ! in the habits graph created in the agenda buffer. It looks like this:

![notvisible](https://user-images.githubusercontent.com/19236996/30208726-1670d6f8-9495-11e7-89c0-0d956a5599e4.png)

What i'm missing is this (not the colors, only * and !):
![missing](https://user-images.githubusercontent.com/19236996/30208939-eec45476-9495-11e7-9122-c3f56b072f10.png)

I did restart emacs after changing the theme. I also made sure that this is not a "theme-independent" problem caused by some mistakes in my .emacs by checking if other themes are working (they are).

Is this issue releated to the theme or am i doing something wrong? Thanks in advance!

**Comment by sjrmanning** [comment]
Sorry I missed this earlier! I don't use habits myself, but this is definitely an issue with the theme.

Can you try using [this gist](https://gist.github.com/sjrmanning/d9440ad9614a108f91e86193e7eb19d4) and see if it fixes the issue? If you're using MELPA you can just paste this version into your darkokai-theme.el :) If it fixes the problem I'll push the changes live into the repo!

**Comment by mschwld** [comment]
Thanks for your reply! I tried it, this is what it looks like:
![new-visibility](https://user-images.githubusercontent.com/19236996/31233234-6bf87448-a9ec-11e7-8db9-0ece2a9bf6b3.png)
Stars & exclemation marks are now visible but only within the green boxes. Inside of the red and "darker green" boxes (createt by org-mode to show that there were reps missing that day) they're still invisible. This is how it looks with noctilux theme enabled:
![nocitlux](https://user-images.githubusercontent.com/19236996/31233567-3f1a2c22-a9ed-11e7-8dcf-4b10e8e642b5.png)

**Comment by sjrmanning** [comment]
Sorry, I've updated the gist with a new version that should fix that.

For now I've just left the foreground as the default. If you have some suggestions though, I'll happily use that instead. Same with the habit colors (you can see these from line [4253](https://gist.github.com/sjrmanning/d9440ad9614a108f91e86193e7eb19d4#file-darkokai-habits-el-L4253)).

**Comment by mschwld** [comment]
Works perfectly fine now. The colours match the rest of the theme very well. Thank you very much for your time & effort. :)
